name = "fx-status"
main = "src/worker.js"
compatibility_date = "2025-03-09"
workers_dev = false
preview_urls = false

kv_namespaces = [
	{ binding = "KV_STATUS", id = "f8230be45d8b4c88ba4994eafa16d0ee", preview_id = "06b189e803d345f1adc8cb2dfa5e8b4b" }
]

[triggers]
crons = ["*/30 * * * *"]

[vars]
notificationChannel = "1279402048541954048"
statusChannel = "1278643839254663220"
statusMessage = "1349033122230046842"
